# Generated by Django 5.1b1 on 2024-07-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('licence', models.FileField(upload_to='')),
            ],
        ),
    ]
