# Generated by Django 5.1b1 on 2024-08-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0003_add_category_add_product_cart_order_details_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='Description',
            new_name='description',
        ),
    ]
