# Generated by Django 3.0 on 2024-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0005_auto_20240809_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/product/'),
        ),
    ]
