# Generated by Django 3.0 on 2024-08-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0006_auto_20240813_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=100)),
                ('House', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister'),
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
