# Generated by Django 3.0 on 2024-08-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0007_auto_20240823_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee_register',
            new_name='EmployeeRegister',
        ),
    ]
