# Generated by Django 3.0 on 2024-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0008_auto_20240824_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopEmployeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('licence', models.FileField(upload_to='')),
                ('psp', models.FileField(upload_to='')),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeRegister',
        ),
    ]
