# Generated by Django 3.0 on 2024-08-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0010_auto_20240827_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopEmployeeRegister1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('licence', models.FileField(upload_to='')),
                ('psp', models.FileField(upload_to='')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('profile_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=100)),
                ('House', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopEmployeeRegister',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister1'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister1'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister1'),
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
