# Generated by Django 3.0 on 2024-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0011_auto_20240827_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister1',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
