# Generated by Django 3.0 on 2024-08-31 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0012_auto_20240829_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=20)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister1')),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
