# Generated by Django 3.0 on 2024-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0013_auto_20240831_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister1',
            name='profile_pic',
            field=models.FileField(blank=True, default='img/profile/default_profile.jpg', null=True, upload_to=''),
        ),
    ]
