# Generated by Django 3.0 on 2024-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0014_auto_20240903_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('profile_pic', models.FileField(blank=True, default='img/profile/default_profile.jpg', null=True, upload_to='')),
            ],
        ),
    ]
