# Generated by Django 3.0 on 2024-10-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0015_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admin_one',
        ),
    ]
