# Generated by Django 3.0 on 2024-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0016_auto_20241008_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_one',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
