# Generated by Django 3.0 on 2024-10-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0017_auto_20241008_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=20)),
                ('cart_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.user_cart')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsone.UserRegister1')),
            ],
        ),
    ]
