# Generated by Django 3.0 on 2024-10-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0018_paid_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='paid_product',
            name='total_price',
        ),
    ]
