# Generated by Django 3.0 on 2024-10-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0019_auto_20241013_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_product',
            name='cart_details',
        ),
    ]
