# Generated by Django 3.0 on 2024-11-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0023_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
