# Generated by Django 3.0 on 2024-11-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0024_delete_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='img/product/')),
                ('p_name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=100)),
            ],
        ),
    ]
