# Generated by Django 3.0 on 2024-11-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0025_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Advertisement',
        ),
    ]
