# Generated by Django 3.0 on 2024-11-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0026_auto_20241106_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
