# Generated by Django 3.0 on 2024-11-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0028_advertisements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisements',
        ),
    ]
