# Generated by Django 3.0 on 2024-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0029_delete_advertisements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='img/product/')),
                ('p_name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=100)),
            ],
        ),
    ]
