# Generated by Django 3.0 on 2024-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsone', '0031_auto_20241111_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister1',
            name='profile_pic',
            field=models.FileField(blank=True, default='img/profiles/default_profile.png', null=True, upload_to=''),
        ),
    ]
